version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: arohyadav
      POSTGRES_DB: form
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  node:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: form
      PGPASSWORD: arohyadav
      PGPORT: 5432
